# Generated by Django 2.1.1 on 2018-10-06 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('quality', models.CharField(choices=[('NEW', 'New'), ('GU', 'Gently Used'), ('MU', 'Moderately Used'), ('RU', 'Rigorously Used')], max_length=3)),
                ('price', models.IntegerField()),
                ('is_sold', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('branch', models.CharField(choices=[('CSIT', 'Computer Science/Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering'), ('CIV', 'Civil Engineering'), ('BIOT', 'Biotechnology'), ('CHEM', 'Chemical Engineering'), ('MECHPROD', 'Mechanical/Production Engineering')], max_length=8)),
                ('sem', models.CharField(choices=[('S1', '1st'), ('S2', '2nd'), ('S3', '3rd'), ('S4', '4th'), ('S5', '5th'), ('S6', '6th'), ('S7', '7th'), ('S8', '8th')], max_length=2)),
                ('description', models.TextField(max_length=1000)),
                ('quality', models.CharField(choices=[('NEW', 'New'), ('GU', 'Gently Used'), ('MU', 'Moderately Used'), ('RU', 'Rigorously Used')], max_length=3)),
                ('price', models.IntegerField()),
                ('is_sold', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('buyer', models.ForeignKey(on_delete=models.SET(None), related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('quality', models.CharField(choices=[('NEW', 'New'), ('GU', 'Gently Used'), ('MU', 'Moderately Used'), ('RU', 'Rigorously Used')], max_length=3)),
                ('price', models.IntegerField()),
                ('is_sold', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
